name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: boots
        run: |
          echo "FOO=$(echo abc)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.FOO }}"    
  secondjob:
    name: secondjob
    runs-on: ubuntu-latest
    steps:
      - name: boots
        run: |
          echo "FOO=$(echo abc)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.FOO }}"    
