name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: boots
        run: |
          echo "abc"
 
