name: CI
on: push
jobs:
  prod-check:
    runs-on: windows
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Deploying to production server on branch ${Env:RUNNER_NAME}"

    - name: one
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

    - name: onefive
      run: echo "${Env:FileContents}"

    - name: json
      run: echo "$(Get-Content -Path ${Env:RUNNER_NAME}.json | ConvertFrom-Json).comport"

    
    - name: two
      run: cat "${Env:RUNNER_NAME}"

    - name: three
      run: cat "${Env:RUNNER_NAME}.env"
