
name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]

jobs:
  prod-check:
    runs-on: windows
    steps:

    - name: develop1
      run: echo "label name = ${Env:github.event.label.name} ${Env:RUNNER_NAME} ${Env:GITHUB_REF}"
      
    - name: develop2
      run: echo "label name = ${Env:github.ref}"

    - name: develop
      if: github.ref == 'refs/heads/develop'   
      run: echo "Deploying to production server on branch"

    - name: baretest label
      if: github.event.label.name == 'baretest'
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

    - name: Both
      if: github.event.label.name == 'baretest' || github.ref == 'refs/heads/develop'   
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

    - name: commit message_
      if: contains(github.event.head_commit.message, 'BARETEST')
      run: echo "hello 123"
      
 all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - develop1
      - develop1
    steps:
      - name: This
        shell: python
        run: |
          import this      
