name: CI
on: push
jobs:
  prod-check:
    runs-on: ubuntu-latest
    container: docker://altendky/ccstudio9:latest
    steps:


    - name: Run a one-line script
      run: echo "Deploying to production server on branch"

    - name: one
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

