name: CI
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows
    steps:
    
    - name: Run a one-line script
      run: echo "Deploying to production server on branch ${Env:RUNNER_NAME}"
