name: CI
on:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  prod-check:
    runs-on: windows
    steps:


    - name: develop
      if: github.ref == 'refs/heads/develop'   
      run: echo "Deploying to production server on branch"

    - name: baretest label
      if: github.event.label.name == 'baretest'
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

